### PR TITLE
Features and Changes for 0.0.2 Release

### PR DESCRIPTION
**Pull request by discreet**
added hyperlink text ability for custom banner
extended if statement to take into account an empty custom banner text
added custom banner to the login page
fixed deprecated plugin initialization behavior
updated required foreman version to 1.9
updated CHANGED.md
updated README.md

### CODE REVIEW

**Comment by jcmcken** [comment]
Everything looks fine. My only issue might be with automatically displaying the banner on the login page. Depending on what information is on the banner, you may not want unauthorized users seeing it. For what I use the banner for that's not an issue, but I can imagine scenarios. I think it might be useful to make that another config flag.

**Comment by jcmcken** [comment]
Take a look at ba55850. Look ok?

**Comment by discreet** [comment]
Looks good. That's pretty much what I started to do last night.

**Comment by jcmcken** [comment]
Cool. Thanks for taking the screenshots by the way. I'll get this stuff released sometime tonight and pushed up to rubygems.org as v0.0.3

**Comment by jcmcken** [comment]
These changes have been released in v0.0.3.

**Pull request closed without merging**
